/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    formats: ['image/avif', 'image/webp'],
    domains: ['fenceworkshop.com', 'cdn.shopify.com'],
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'fenceworkshop.com',
      },
      {
        protocol: 'https',
        hostname: 'cdn.shopify.com',
      },
    ],
  },
  async redirects() {
    return [

      // ── Legal pages ────────────────────────────────────────────────────────

      { source: '/terms-and-conditions', destination: '/terms/', permanent: true },
      { source: '/terms-and-conditions/', destination: '/terms/', permanent: true },

      // ── Pages ──────────────────────────────────────────────────────────────

      { source: '/contact-us', destination: '/contact/', permanent: true },
      { source: '/contact-us/', destination: '/contact/', permanent: true },
      { source: '/thank-you-for-contacting', destination: '/thank-you/', permanent: true },
      { source: '/thank-you-for-contacting/', destination: '/thank-you/', permanent: true },
      { source: '/our-story', destination: '/about-us/', permanent: true },
      { source: '/our-story/', destination: '/about-us/', permanent: true },
      { source: '/our-promise', destination: '/about-us/', permanent: true },
      { source: '/our-promise/', destination: '/about-us/', permanent: true },
      { source: '/locations', destination: '/installation/service-areas/', permanent: true },
      { source: '/locations/', destination: '/installation/service-areas/', permanent: true },
      { source: '/installation', destination: '/installation/georgia/commercial-fence-installation/', permanent: true },
      { source: '/installation/', destination: '/installation/georgia/commercial-fence-installation/', permanent: true },
      { source: '/returns-exchanges', destination: '/contact/', permanent: true },
      { source: '/returns-exchanges/', destination: '/contact/', permanent: true },
      { source: '/shipping-information', destination: '/contact/', permanent: true },
      { source: '/shipping-information/', destination: '/contact/', permanent: true },
      { source: '/order-tracking', destination: '/contact/', permanent: true },
      { source: '/order-tracking/', destination: '/contact/', permanent: true },
      { source: '/pool-regulations-and-codes', destination: '/shop/resources/pool-code-aluminum-fence/', permanent: true },
      { source: '/pool-regulations-and-codes/', destination: '/shop/resources/pool-code-aluminum-fence/', permanent: true },

      // ── Commercial installation pages ──────────────────────────────────────

      { source: '/dumpster-garbage-enclosures-gates-atlanta', destination: '/installation/georgia/dumpster-enclosure-gates/', permanent: true },
      { source: '/dumpster-garbage-enclosures-gates-atlanta/', destination: '/installation/georgia/dumpster-enclosure-gates/', permanent: true },
      { source: '/commercial', destination: '/installation/georgia/commercial-fence-installation/', permanent: true },
      { source: '/commercial/', destination: '/installation/georgia/commercial-fence-installation/', permanent: true },
      { source: '/industrial', destination: '/installation/georgia/commercial-fence-installation/', permanent: true },
      { source: '/industrial/', destination: '/installation/georgia/commercial-fence-installation/', permanent: true },
      { source: '/commercial-fence-installation-georgia', destination: '/installation/georgia/commercial-fence-installation/', permanent: true },
      { source: '/commercial-fence-installation-georgia/', destination: '/installation/georgia/commercial-fence-installation/', permanent: true },
      { source: '/commercial-fence-installation-services', destination: '/installation/georgia/commercial-fence-installation/', permanent: true },
      { source: '/commercial-fence-installation-services/', destination: '/installation/georgia/commercial-fence-installation/', permanent: true },
      { source: '/commercial-fence-company', destination: '/installation/georgia/commercial-fence-installation/', permanent: true },
      { source: '/commercial-fence-company/', destination: '/installation/georgia/commercial-fence-installation/', permanent: true },
      { source: '/georgia-commercial-fence-installation', destination: '/installation/georgia/commercial-fence-installation/', permanent: true },
      { source: '/georgia-commercial-fence-installation/', destination: '/installation/georgia/commercial-fence-installation/', permanent: true },
      { source: '/residential-fence-installation-services', destination: '/installation/georgia/residential-fence-installation/', permanent: true },
      { source: '/residential-fence-installation-services/', destination: '/installation/georgia/residential-fence-installation/', permanent: true },
      { source: '/residential-fence-company', destination: '/installation/georgia/residential-fence-installation/', permanent: true },
      { source: '/residential-fence-company/', destination: '/installation/georgia/residential-fence-installation/', permanent: true },
      { source: '/residential', destination: '/installation/georgia/residential-fence-installation/', permanent: true },
      { source: '/residential/', destination: '/installation/georgia/residential-fence-installation/', permanent: true },
      { source: '/commercial-chain-link-fence-gate-installation', destination: '/installation/georgia/commercial-chain-link-fence/', permanent: true },
      { source: '/commercial-chain-link-fence-gate-installation/', destination: '/installation/georgia/commercial-chain-link-fence/', permanent: true },
      { source: '/commercial-chain-link-fence-atlanta', destination: '/installation/georgia/commercial-chain-link-fence/', permanent: true },
      { source: '/commercial-chain-link-fence-atlanta/', destination: '/installation/georgia/commercial-chain-link-fence/', permanent: true },
      { source: '/commercial-ornamental-fence-gate-installation', destination: '/installation/georgia/aluminum-fence-installation/', permanent: true },
      { source: '/commercial-ornamental-fence-gate-installation/', destination: '/installation/georgia/aluminum-fence-installation/', permanent: true },
      { source: '/commercial-parking-deck-fence-installation', destination: '/installation/georgia/parking-garage-fencing/', permanent: true },
      { source: '/commercial-parking-deck-fence-installation/', destination: '/installation/georgia/parking-garage-fencing/', permanent: true },
      { source: '/commercial-warehouse-fencing-installation', destination: '/installation/georgia/warehouse-partitions/', permanent: true },
      { source: '/commercial-warehouse-fencing-installation/', destination: '/installation/georgia/warehouse-partitions/', permanent: true },
      { source: '/commercial-safety-railing-bollard-installation', destination: '/installation/georgia/bollard-installation/', permanent: true },
      { source: '/commercial-safety-railing-bollard-installation/', destination: '/installation/georgia/bollard-installation/', permanent: true },
      { source: '/commercial-pedestrian-gate-installation', destination: '/installation/georgia/security-gate-systems/', permanent: true },
      { source: '/commercial-pedestrian-gate-installation/', destination: '/installation/georgia/security-gate-systems/', permanent: true },
      { source: '/commercial-driveway-gate-installation', destination: '/installation/georgia/slide-gates/', permanent: true },
      { source: '/commercial-driveway-gate-installation/', destination: '/installation/georgia/slide-gates/', permanent: true },

      // ── Shop / product category pages ──────────────────────────────────────

      { source: '/buy-aluminum-fencing', destination: '/shop/aluminum-fencing/', permanent: true },
      { source: '/buy-aluminum-fencing/', destination: '/shop/aluminum-fencing/', permanent: true },
      { source: '/shop-all-aluminum-fence-materials', destination: '/shop/', permanent: true },
      { source: '/shop-all-aluminum-fence-materials/', destination: '/shop/', permanent: true },
      { source: '/buy-aluminum-walk-gate-kits', destination: '/shop/walk-gates/', permanent: true },
      { source: '/buy-aluminum-walk-gate-kits/', destination: '/shop/walk-gates/', permanent: true },
      { source: '/buy-aluminum-driveway-gates', destination: '/shop/driveway-gates/', permanent: true },
      { source: '/buy-aluminum-driveway-gates/', destination: '/shop/driveway-gates/', permanent: true },
      { source: '/buy-aluminum-fence-accessories', destination: '/shop/accessories/', permanent: true },
      { source: '/buy-aluminum-fence-accessories/', destination: '/shop/accessories/', permanent: true },

      // Old WooCommerce category/taxonomy pages
      { source: '/fence-supplies/:path*', destination: '/shop/', permanent: true },
      { source: '/product-category/:path*', destination: '/shop/', permanent: true },

      // ── Missing commercial pages (gaps found during audit) ────────────────

      { source: '/custom-commercial-steel-aluminum-railing-installation', destination: '/installation/georgia/bollard-installation/', permanent: true },
      { source: '/custom-commercial-steel-aluminum-railing-installation/', destination: '/installation/georgia/bollard-installation/', permanent: true },
      { source: '/commercial-warehouse-cage-installation', destination: '/installation/georgia/warehouse-partitions/', permanent: true },
      { source: '/commercial-warehouse-cage-installation/', destination: '/installation/georgia/warehouse-partitions/', permanent: true },
      { source: '/access-control-systems-atlanta-ga', destination: '/installation/georgia/security-gate-systems/', permanent: true },
      { source: '/access-control-systems-atlanta-ga/', destination: '/installation/georgia/security-gate-systems/', permanent: true },
      { source: '/electric-gates-atlanta-ga', destination: '/installation/georgia/security-gate-systems/', permanent: true },
      { source: '/electric-gates-atlanta-ga/', destination: '/installation/georgia/security-gate-systems/', permanent: true },
      { source: '/security-gates-atlanta-ga', destination: '/installation/georgia/security-gate-systems/', permanent: true },
      { source: '/security-gates-atlanta-ga/', destination: '/installation/georgia/security-gate-systems/', permanent: true },
      { source: '/wrought-iron-fence-atlanta-ga', destination: '/installation/georgia/residential-fence-installation/', permanent: true },
      { source: '/wrought-iron-fence-atlanta-ga/', destination: '/installation/georgia/residential-fence-installation/', permanent: true },
      { source: '/fence-companies-atlanta-ga', destination: '/installation/georgia/commercial-fence-installation/', permanent: true },
      { source: '/fence-companies-atlanta-ga/', destination: '/installation/georgia/commercial-fence-installation/', permanent: true },
      { source: '/atlanta-fence-company-reviews', destination: '/about-us/', permanent: true },
      { source: '/atlanta-fence-company-reviews/', destination: '/about-us/', permanent: true },
      { source: '/security-fences-atlanta', destination: '/installation/georgia/commercial-security-fence/', permanent: true },
      { source: '/security-fences-atlanta/', destination: '/installation/georgia/commercial-security-fence/', permanent: true },
      { source: '/7-benefits-of-aluminum-fencing', destination: '/shop/resources/aluminum-vs-steel-fencing/', permanent: true },
      { source: '/7-benefits-of-aluminum-fencing/', destination: '/shop/resources/aluminum-vs-steel-fencing/', permanent: true },
      { source: '/custom-gates-atlanta-ga', destination: '/installation/georgia/residential-fence-installation/', permanent: true },
      { source: '/custom-gates-atlanta-ga/', destination: '/installation/georgia/residential-fence-installation/', permanent: true },
      { source: '/custom-wood-driveway-gates-atlanta-ga', destination: '/installation/georgia/residential-fence-installation/', permanent: true },
      { source: '/custom-wood-driveway-gates-atlanta-ga/', destination: '/installation/georgia/residential-fence-installation/', permanent: true },
      { source: '/vinyl-privacy-fence-atlanta-ga', destination: '/installation/georgia/residential-fence-installation/', permanent: true },
      { source: '/vinyl-privacy-fence-atlanta-ga/', destination: '/installation/georgia/residential-fence-installation/', permanent: true },
      { source: '/ornamental-metal-fences-atlanta-ga', destination: '/installation/georgia/aluminum-fence-installation/', permanent: true },
      { source: '/ornamental-metal-fences-atlanta-ga/', destination: '/installation/georgia/aluminum-fence-installation/', permanent: true },
      { source: '/atlanta-fences-and-gates', destination: '/installation/georgia/commercial-fence-installation/', permanent: true },
      { source: '/atlanta-fences-and-gates/', destination: '/installation/georgia/commercial-fence-installation/', permanent: true },
      { source: '/perimeter-security-fence', destination: '/installation/georgia/commercial-security-fence/', permanent: true },
      { source: '/perimeter-security-fence/', destination: '/installation/georgia/commercial-security-fence/', permanent: true },
      { source: '/black-chain-link-fence', destination: '/shop/chain-link-fencing/', permanent: true },
      { source: '/black-chain-link-fence/', destination: '/shop/chain-link-fencing/', permanent: true },
      { source: '/commercial-black-chain-link', destination: '/installation/georgia/commercial-chain-link-fence/', permanent: true },
      { source: '/commercial-black-chain-link/', destination: '/installation/georgia/commercial-chain-link-fence/', permanent: true },
      { source: '/residential-galvanized-chain-link', destination: '/shop/chain-link-fencing/', permanent: true },
      { source: '/residential-galvanized-chain-link/', destination: '/shop/chain-link-fencing/', permanent: true },

      // ── Old /product/ URLs → new /shop/ URLs ───────────────────────────────

      // Driveway Gates
      { source: '/product/athens-double-driveway-gate', destination: '/shop/driveway-gates/athens-double-driveway-gate/', permanent: true },
      { source: '/product/atlanta-double-driveway-gate', destination: '/shop/driveway-gates/atlanta-double-driveway-gate/', permanent: true },
      { source: '/product/avalon-double-driveway-gate', destination: '/shop/driveway-gates/avalon-double-driveway-gate/', permanent: true },
      { source: '/product/berkley-double-driveway-gate', destination: '/shop/driveway-gates/berkley-double-driveway-gate/', permanent: true },
      { source: '/product/brookhaven-double-driveway-gate', destination: '/shop/driveway-gates/brookhaven-double-driveway-gate/', permanent: true },
      { source: '/product/buford-double-driveway-gate', destination: '/shop/driveway-gates/buford-double-driveway-gate/', permanent: true },
      { source: '/product/candler-double-driveway-gate', destination: '/shop/driveway-gates/candler-double-driveway-gate/', permanent: true },
      { source: '/product/chamblee-double-driveway-gate', destination: '/shop/driveway-gates/chamblee-double-driveway-gate/', permanent: true },
      { source: '/product/cobb-double-driveway-gate', destination: '/shop/driveway-gates/cobb-double-driveway-gate/', permanent: true },
      { source: '/product/dawson-double-driveway-gate', destination: '/shop/driveway-gates/dawson-double-driveway-gate/', permanent: true },
      { source: '/product/dublin-double-driveway-gate', destination: '/shop/driveway-gates/dublin-double-driveway-gate/', permanent: true },
      { source: '/product/dunwoody-double-driveway-gate', destination: '/shop/driveway-gates/dunwoody-double-driveway-gate/', permanent: true },
      { source: '/product/savannah-double-driveway-gate', destination: '/shop/driveway-gates/savannah-double-driveway-gate/', permanent: true },
      { source: '/product/sharpsburg-double-driveway-gate', destination: '/shop/driveway-gates/sharpsburg-double-driveway-gate/', permanent: true },
      { source: '/product/ellijay-double-driveway-gate', destination: '/shop/driveway-gates/ellijay-double-driveway-gate/', permanent: true },
      { source: '/product/emory-double-driveway-gate', destination: '/shop/driveway-gates/emory-double-driveway-gate/', permanent: true },

      // Walk Gates
      { source: '/product/athens-walk-gate', destination: '/shop/walk-gates/athens-walk-gate/', permanent: true },
      { source: '/product/atlanta-walk-gate', destination: '/shop/walk-gates/atlanta-walk-gate/', permanent: true },
      { source: '/product/avalon-walk-gate', destination: '/shop/walk-gates/avalon-walk-gate/', permanent: true },
      { source: '/product/berkley-walk-gate', destination: '/shop/walk-gates/berkley-walk-gate/', permanent: true },
      { source: '/product/brookhaven-walk-gate', destination: '/shop/walk-gates/brookhaven-walk-gate/', permanent: true },
      { source: '/product/buford-walk-gate', destination: '/shop/walk-gates/buford-walk-gate/', permanent: true },
      { source: '/product/candler-walk-gate', destination: '/shop/walk-gates/candler-walk-gate/', permanent: true },
      { source: '/product/chamblee-walk-gate', destination: '/shop/walk-gates/chamblee-walk-gate/', permanent: true },
      { source: '/product/cobb-walk-gate', destination: '/shop/walk-gates/cobb-walk-gate/', permanent: true },
      { source: '/product/dawson-walk-gate', destination: '/shop/walk-gates/dawson-walk-gate/', permanent: true },
      { source: '/product/dublin-walk-gate', destination: '/shop/walk-gates/dublin-walk-gate/', permanent: true },
      { source: '/product/dunwoody-walk-gate', destination: '/shop/walk-gates/dunwoody-walk-gate/', permanent: true },
      { source: '/product/savannah-walk-gate', destination: '/shop/walk-gates/savannah-walk-gate/', permanent: true },
      { source: '/product/sharpsburg-walk-gate', destination: '/shop/walk-gates/sharpsburg-walk-gate/', permanent: true },
      { source: '/product/ellijay-walk-gate', destination: '/shop/walk-gates/ellijay-walk-gate/', permanent: true },
      { source: '/product/emory-walk-gate', destination: '/shop/walk-gates/emory-walk-gate/', permanent: true },

      // Fence Panels
      { source: '/product/athens-panel', destination: '/shop/aluminum-fencing/athens-fence-panel/', permanent: true },
      { source: '/product/atlanta-panel', destination: '/shop/aluminum-fencing/atlanta-fence-panel/', permanent: true },
      { source: '/product/avalon-panel', destination: '/shop/aluminum-fencing/avalon-fence-panel/', permanent: true },
      { source: '/product/berkley-panel', destination: '/shop/aluminum-fencing/berkley-fence-panel/', permanent: true },
      { source: '/product/brookhaven-panel', destination: '/shop/aluminum-fencing/brookhaven-fence-panel/', permanent: true },
      { source: '/product/buford-panel', destination: '/shop/aluminum-fencing/buford-fence-panel/', permanent: true },
      { source: '/product/candler-panel', destination: '/shop/aluminum-fencing/candler-fence-panel/', permanent: true },
      { source: '/product/chamblee-panel', destination: '/shop/aluminum-fencing/chamblee-fence-panel/', permanent: true },
      { source: '/product/cobb-panel', destination: '/shop/aluminum-fencing/cobb-fence-panel/', permanent: true },
      { source: '/product/dawson-panel', destination: '/shop/aluminum-fencing/dawson-fence-panel/', permanent: true },
      { source: '/product/dublin-panel', destination: '/shop/aluminum-fencing/dublin-fence-panel/', permanent: true },
      { source: '/product/dunwoody-panel', destination: '/shop/aluminum-fencing/dunwoody-fence-panel/', permanent: true },
      { source: '/product/savannah-panel', destination: '/shop/aluminum-fencing/savannah-fence-panel/', permanent: true },
      { source: '/product/sharpsburg-panel', destination: '/shop/aluminum-fencing/sharpsburg-fence-panel/', permanent: true },

      // Fence Posts (no dedicated posts category; redirect to aluminum fencing)
      { source: '/product/athens-fence-posts', destination: '/shop/aluminum-fencing/athens-fence-panel/', permanent: true },
      { source: '/product/atlanta-fence-posts', destination: '/shop/aluminum-fencing/atlanta-fence-panel/', permanent: true },
      { source: '/product/avalon-fence-posts', destination: '/shop/aluminum-fencing/avalon-fence-panel/', permanent: true },
      { source: '/product/berkley-fence-posts', destination: '/shop/aluminum-fencing/berkley-fence-panel/', permanent: true },
      { source: '/product/brookhaven-fence-posts', destination: '/shop/aluminum-fencing/brookhaven-fence-panel/', permanent: true },
      { source: '/product/buford-fence-posts', destination: '/shop/aluminum-fencing/buford-fence-panel/', permanent: true },
      { source: '/product/candler-fence-posts', destination: '/shop/aluminum-fencing/candler-fence-panel/', permanent: true },
      { source: '/product/chamblee-fence-posts', destination: '/shop/aluminum-fencing/chamblee-fence-panel/', permanent: true },
      { source: '/product/cobb-fence-posts', destination: '/shop/aluminum-fencing/cobb-fence-panel/', permanent: true },
      { source: '/product/dawson-fence-posts', destination: '/shop/aluminum-fencing/dawson-fence-panel/', permanent: true },
      { source: '/product/dublin-fence-posts', destination: '/shop/aluminum-fencing/dublin-fence-panel/', permanent: true },
      { source: '/product/dunwoody-fence-posts', destination: '/shop/aluminum-fencing/dunwoody-fence-panel/', permanent: true },
      { source: '/product/savannah-fence-posts', destination: '/shop/aluminum-fencing/savannah-fence-panel/', permanent: true },
      { source: '/product/sharpsburg-fence-posts', destination: '/shop/aluminum-fencing/sharpsburg-fence-panel/', permanent: true },

      // Accessories
      { source: '/product/aluminum-post-cap', destination: '/shop/accessories/aluminum-post-cap/', permanent: true },
      { source: '/product/gate-gravity-latch', destination: '/shop/accessories/gate-gravity-latch/', permanent: true },
      { source: '/product/post-deck-mount', destination: '/shop/accessories/post-deck-mount/', permanent: true },
      { source: '/product/safetech-3-5-adjustable-tension-gate-hinge-set', destination: '/shop/accessories/safetech-3-5-adjustable-tension-gate-hinge-set/', permanent: true },
      { source: '/product/self-tapping-post-screws', destination: '/shop/accessories/self-tapping-post-screws/', permanent: true },
      { source: '/product/standard-drop-rod', destination: '/shop/accessories/standard-drop-rod/', permanent: true },
      { source: '/product/wall-mounts', destination: '/shop/accessories/wall-mounts/', permanent: true },
      { source: '/product/dd-series-3-top-pull-20-5-magnalatch-gate-latch', destination: '/shop/accessories/dd-series-3-top-pull-20-5-magnalatch-gate-latch/', permanent: true },
      { source: '/product/dd-vertical-pull-10-25-magnalatch-gate-latch', destination: '/shop/accessories/dd-vertical-pull-10-25-magnalatch-gate-latch/', permanent: true },

      // Fence Kits (old generic kit slugs → specific Brookhaven kits)
      { source: '/product/all-inclusive-100ft-fence-kit', destination: '/shop/fence-kits/brookhaven-100ft-fence-kit/', permanent: true },
      { source: '/product/all-inclusive-100ft-fence-kit/', destination: '/shop/fence-kits/brookhaven-100ft-fence-kit/', permanent: true },
      { source: '/product/all-inclusive-150ft-fence-kit', destination: '/shop/fence-kits/brookhaven-150ft-fence-kit/', permanent: true },
      { source: '/product/all-inclusive-150ft-fence-kit/', destination: '/shop/fence-kits/brookhaven-150ft-fence-kit/', permanent: true },
      { source: '/product/all-inclusive-200ft-fence-kit', destination: '/shop/fence-kits/brookhaven-200ft-fence-kit/', permanent: true },
      { source: '/product/all-inclusive-200ft-fence-kit/', destination: '/shop/fence-kits/brookhaven-200ft-fence-kit/', permanent: true },
      { source: '/product/all-inclusive-250ft-fence-kit', destination: '/shop/fence-kits/brookhaven-250ft-fence-kit/', permanent: true },
      { source: '/product/all-inclusive-250ft-fence-kit/', destination: '/shop/fence-kits/brookhaven-250ft-fence-kit/', permanent: true },
      { source: '/product/choose-your-kit', destination: '/shop/fence-kits/', permanent: true },
      { source: '/product/choose-your-kit/', destination: '/shop/fence-kits/', permanent: true },

      // Catch-all: any remaining /product/ URL → shop
      { source: '/product/:slug', destination: '/shop/', permanent: true },

    ]
  },
}

module.exports = nextConfig
